Move Interfaces to behavior
Problem:
/Users/katjasuss/Plone/trainingmasteringplone/backend/eggs/plone.dexterity-2.10.0-py3.8.egg/plone/dexterity/schema.py:177: DeprecationWarning: No behavior registration found for behavior named "starzel.votable_behavior.interfaces.IVoting" for factory "talk" - trying deprecated fallback lookup (will be removed in 3.0)..."
  warnings.warn(
2021-04-24 10:59:35,656 ERROR   [plone.dexterity.schema:38][waitress-0] Error resolving behavior starzel.votable_behavior.interfaces.IVoting for factory talk

Problem:
setter for votes and voted is missing. We do not want this, as we do want to use method vote to set votes and voted.

2021-04-24 10:55:45,968 ERROR   [Zope.SiteErrorLog:17][waitress-1] 1619254545.9678540.9929965349995861 http://localhost:8080/Plone/testseiten/++add++talk
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 266, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module Products.PDBDebugMode.wsgi_runcall, line 60, in pdb_runcall
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.dexterity.browser.add, line 141, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 22, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.dexterity.browser.add, line 116, in handleAdd
  Module z3c.form.form, line 263, in createAndAdd
  Module plone.dexterity.browser.add, line 84, in create
  Module plone.dexterity.browser.add, line 200, in _applyChanges
  Module z3c.form.datamanager, line 91, in set
AttributeError: can't set attribute

Some documentation added.